#!/usr/bin/env python3
"""Generate a realistic seed dataset of popular streamer clips."""

import csv
import json

CLIPS = [
    # ── Twitch ────────────────────────────────────────────────────────────────
    {
        "platform": "twitch",
        "game": "Just Chatting",
        "clip_id": "TwitchClip001",
        "title": "xQc reacts to insane IRL moment",
        "channel": "xQcOW",
        "channel_url": "https://twitch.tv/xqcow",
        "creator": "viewer_clip1",
        "view_count": 4820000,
        "duration_sec": 58,
        "created_at": "2025-05-06T14:22:11Z",
        "url": "https://clips.twitch.tv/TwitchClip001",
        "thumbnail_url": "https://clips-media-assets2.twitch.tv/TwitchClip001-preview-480x272.jpg",
    },
    {
        "platform": "twitch",
        "game": "Fortnite",
        "clip_id": "TwitchClip002",
        "title": "Ninja 200m snipe no scope",
        "channel": "Ninja",
        "channel_url": "https://twitch.tv/ninja",
        "creator": "clips_fan22",
        "view_count": 3910000,
        "duration_sec": 34,
        "created_at": "2025-05-07T20:05:44Z",
        "url": "https://clips.twitch.tv/TwitchClip002",
        "thumbnail_url": "https://clips-media-assets2.twitch.tv/TwitchClip002-preview-480x272.jpg",
    },
    {
        "platform": "twitch",
        "game": "Grand Theft Auto V",
        "clip_id": "TwitchClip003",
        "title": "NoPixel RP goes completely off script",
        "channel": "Sykkuno",
        "channel_url": "https://twitch.tv/sykkuno",
        "creator": "gtarp_clips",
        "view_count": 3450000,
        "duration_sec": 72,
        "created_at": "2025-05-08T18:11:30Z",
        "url": "https://clips.twitch.tv/TwitchClip003",
        "thumbnail_url": "https://clips-media-assets2.twitch.tv/TwitchClip003-preview-480x272.jpg",
    },
    {
        "platform": "twitch",
        "game": "League of Legends",
        "clip_id": "TwitchClip004",
        "title": "Tyler1 hits Challenger — instant freakout",
        "channel": "loltyler1",
        "channel_url": "https://twitch.tv/loltyler1",
        "creator": "lol_moments",
        "view_count": 2980000,
        "duration_sec": 45,
        "created_at": "2025-05-09T22:40:00Z",
        "url": "https://clips.twitch.tv/TwitchClip004",
        "thumbnail_url": "https://clips-media-assets2.twitch.tv/TwitchClip004-preview-480x272.jpg",
    },
    {
        "platform": "twitch",
        "game": "Minecraft",
        "clip_id": "TwitchClip005",
        "title": "Dream speedrun world record attempt",
        "channel": "Dream",
        "channel_url": "https://twitch.tv/dream",
        "creator": "mc_clips_hq",
        "view_count": 2750000,
        "duration_sec": 88,
        "created_at": "2025-05-05T16:30:22Z",
        "url": "https://clips.twitch.tv/TwitchClip005",
        "thumbnail_url": "https://clips-media-assets2.twitch.tv/TwitchClip005-preview-480x272.jpg",
    },
    {
        "platform": "twitch",
        "game": "Valorant",
        "clip_id": "TwitchClip006",
        "title": "Shroud 1v5 clutch — chat explodes",
        "channel": "shroud",
        "channel_url": "https://twitch.tv/shroud",
        "creator": "val_highlight_reel",
        "view_count": 2510000,
        "duration_sec": 41,
        "created_at": "2025-05-10T21:15:09Z",
        "url": "https://clips.twitch.tv/TwitchClip006",
        "thumbnail_url": "https://clips-media-assets2.twitch.tv/TwitchClip006-preview-480x272.jpg",
    },
    {
        "platform": "twitch",
        "game": "Counter-Strike 2",
        "clip_id": "TwitchClip007",
        "title": "s1mple AWP ace through smoke",
        "channel": "s1mple",
        "channel_url": "https://twitch.tv/s1mple",
        "creator": "cs_clips_pro",
        "view_count": 2200000,
        "duration_sec": 29,
        "created_at": "2025-05-11T19:05:55Z",
        "url": "https://clips.twitch.tv/TwitchClip007",
        "thumbnail_url": "https://clips-media-assets2.twitch.tv/TwitchClip007-preview-480x272.jpg",
    },
    {
        "platform": "twitch",
        "game": "Apex Legends",
        "clip_id": "TwitchClip008",
        "title": "ImperialHal predator rank 1 solo push",
        "channel": "TSM_ImperialHal",
        "channel_url": "https://twitch.tv/tsm_imperialhal",
        "creator": "apex_clips_tv",
        "view_count": 1970000,
        "duration_sec": 52,
        "created_at": "2025-05-12T17:44:18Z",
        "url": "https://clips.twitch.tv/TwitchClip008",
        "thumbnail_url": "https://clips-media-assets2.twitch.tv/TwitchClip008-preview-480x272.jpg",
    },
    {
        "platform": "twitch",
        "game": "Just Chatting",
        "clip_id": "TwitchClip009",
        "title": "Pokimane's surprise announcement",
        "channel": "pokimane",
        "channel_url": "https://twitch.tv/pokimane",
        "creator": "poki_moments",
        "view_count": 1850000,
        "duration_sec": 63,
        "created_at": "2025-05-04T15:20:00Z",
        "url": "https://clips.twitch.tv/TwitchClip009",
        "thumbnail_url": "https://clips-media-assets2.twitch.tv/TwitchClip009-preview-480x272.jpg",
    },
    {
        "platform": "twitch",
        "game": "World of Warcraft",
        "clip_id": "TwitchClip010",
        "title": "Asmongold first reaction to new patch reveal",
        "channel": "Asmongold",
        "channel_url": "https://twitch.tv/asmongold",
        "creator": "asmong_clips",
        "view_count": 1640000,
        "duration_sec": 77,
        "created_at": "2025-05-03T20:10:45Z",
        "url": "https://clips.twitch.tv/TwitchClip010",
        "thumbnail_url": "https://clips-media-assets2.twitch.tv/TwitchClip010-preview-480x272.jpg",
    },
    # ── Kick ──────────────────────────────────────────────────────────────────
    {
        "platform": "kick",
        "game": "Grand Theft Auto V",
        "clip_id": "KickClip001",
        "title": "xQc goes full rage mode on NoPixel server",
        "channel": "xqc",
        "channel_url": "https://kick.com/xqc",
        "creator": "xqc",
        "view_count": 5100000,
        "duration_sec": 60,
        "created_at": "2025-05-08T03:15:00Z",
        "url": "https://kick.com/xqc/clips/KickClip001",
        "thumbnail_url": "https://clips.kick.com/clips/KickClip001/thumbnail.jpg",
    },
    {
        "platform": "kick",
        "game": "Just Chatting",
        "clip_id": "KickClip002",
        "title": "Adin Ross celebrity guest goes viral",
        "channel": "adinross",
        "channel_url": "https://kick.com/adinross",
        "creator": "adinross",
        "view_count": 4300000,
        "duration_sec": 48,
        "created_at": "2025-05-09T22:00:00Z",
        "url": "https://kick.com/adinross/clips/KickClip002",
        "thumbnail_url": "https://clips.kick.com/clips/KickClip002/thumbnail.jpg",
    },
    {
        "platform": "kick",
        "game": "Slots",
        "clip_id": "KickClip003",
        "title": "Trainwreck $500k jackpot hit live",
        "channel": "trainwreckstv",
        "channel_url": "https://kick.com/trainwreckstv",
        "creator": "trainwreckstv",
        "view_count": 3800000,
        "duration_sec": 35,
        "created_at": "2025-05-07T01:30:00Z",
        "url": "https://kick.com/trainwreckstv/clips/KickClip003",
        "thumbnail_url": "https://clips.kick.com/clips/KickClip003/thumbnail.jpg",
    },
    {
        "platform": "kick",
        "game": "IRL",
        "clip_id": "KickClip004",
        "title": "N3on confronted at public event",
        "channel": "n3on",
        "channel_url": "https://kick.com/n3on",
        "creator": "n3on",
        "view_count": 3100000,
        "duration_sec": 90,
        "created_at": "2025-05-06T14:00:00Z",
        "url": "https://kick.com/n3on/clips/KickClip004",
        "thumbnail_url": "https://clips.kick.com/clips/KickClip004/thumbnail.jpg",
    },
    {
        "platform": "kick",
        "game": "Fortnite",
        "clip_id": "KickClip005",
        "title": "Clix drops 30 kills in ranked — insane game",
        "channel": "clix",
        "channel_url": "https://kick.com/clix",
        "creator": "clix",
        "view_count": 2400000,
        "duration_sec": 55,
        "created_at": "2025-05-10T18:45:00Z",
        "url": "https://kick.com/clix/clips/KickClip005",
        "thumbnail_url": "https://clips.kick.com/clips/KickClip005/thumbnail.jpg",
    },
    {
        "platform": "kick",
        "game": "Just Chatting",
        "clip_id": "KickClip006",
        "title": "Sketch hits 500k subs — emotional moment",
        "channel": "sketch",
        "channel_url": "https://kick.com/sketch",
        "creator": "sketch",
        "view_count": 2050000,
        "duration_sec": 42,
        "created_at": "2025-05-11T20:30:00Z",
        "url": "https://kick.com/sketch/clips/KickClip006",
        "thumbnail_url": "https://clips.kick.com/clips/KickClip006/thumbnail.jpg",
    },
    # ── YouTube ───────────────────────────────────────────────────────────────
    {
        "platform": "youtube",
        "game": "",
        "clip_id": "YT_abc123def",
        "title": "Best Twitch Clips of The Week #247",
        "channel": "Daily Dose of Twitch",
        "channel_url": "",
        "creator": "Daily Dose of Twitch",
        "view_count": 8900000,
        "duration_sec": 0,
        "created_at": "4 days ago",
        "url": "https://www.youtube.com/watch?v=YT_abc123def",
        "thumbnail_url": "https://i.ytimg.com/vi/YT_abc123def/hqdefault.jpg",
    },
    {
        "platform": "youtube",
        "game": "",
        "clip_id": "YT_xyz789ghi",
        "title": "Kick Clips That Broke The Internet",
        "channel": "Kick Highlights",
        "channel_url": "",
        "creator": "Kick Highlights",
        "view_count": 6700000,
        "duration_sec": 0,
        "created_at": "6 days ago",
        "url": "https://www.youtube.com/watch?v=YT_xyz789ghi",
        "thumbnail_url": "https://i.ytimg.com/vi/YT_xyz789ghi/hqdefault.jpg",
    },
    {
        "platform": "youtube",
        "game": "",
        "clip_id": "YT_mno456pqr",
        "title": "xQc Most Viewed Moments 2025",
        "channel": "xQc Highlights",
        "channel_url": "",
        "creator": "xQc Highlights",
        "view_count": 5500000,
        "duration_sec": 0,
        "created_at": "1 week ago",
        "url": "https://www.youtube.com/watch?v=YT_mno456pqr",
        "thumbnail_url": "https://i.ytimg.com/vi/YT_mno456pqr/hqdefault.jpg",
    },
    {
        "platform": "youtube",
        "game": "",
        "clip_id": "YT_rst012uvw",
        "title": "Streamers React to Crazy Clip Compilations",
        "channel": "StreamerMoments",
        "channel_url": "",
        "creator": "StreamerMoments",
        "view_count": 4100000,
        "duration_sec": 0,
        "created_at": "3 days ago",
        "url": "https://www.youtube.com/watch?v=YT_rst012uvw",
        "thumbnail_url": "https://i.ytimg.com/vi/YT_rst012uvw/hqdefault.jpg",
    },
    {
        "platform": "youtube",
        "game": "",
        "clip_id": "YT_jkl345mno",
        "title": "Ninja vs MrBeast — Fortnite 1v1 highlights",
        "channel": "Gaming Central",
        "channel_url": "",
        "creator": "Gaming Central",
        "view_count": 3600000,
        "duration_sec": 0,
        "created_at": "5 days ago",
        "url": "https://www.youtube.com/watch?v=YT_jkl345mno",
        "thumbnail_url": "https://i.ytimg.com/vi/YT_jkl345mno/hqdefault.jpg",
    },
    {
        "platform": "youtube",
        "game": "",
        "clip_id": "YT_pqr678stu",
        "title": "Most Insane Twitch Moments This Month",
        "channel": "TwitchRecap",
        "channel_url": "",
        "creator": "TwitchRecap",
        "view_count": 2900000,
        "duration_sec": 0,
        "created_at": "2 days ago",
        "url": "https://www.youtube.com/watch?v=YT_pqr678stu",
        "thumbnail_url": "https://i.ytimg.com/vi/YT_pqr678stu/hqdefault.jpg",
    },
]

# Sort by view count descending
CLIPS.sort(key=lambda c: c["view_count"], reverse=True)


def write_seed():
    with open("clips.json", "w", encoding="utf-8") as fh:
        json.dump(CLIPS, fh, indent=2, ensure_ascii=False)
    print(f"Wrote {len(CLIPS)} clips -> clips.json")

    with open("clips.csv", "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(CLIPS[0].keys()))
        writer.writeheader()
        writer.writerows(CLIPS)
    print(f"Wrote {len(CLIPS)} clips -> clips.csv")

    print("\nTop 10 by view count:")
    for i, c in enumerate(CLIPS[:10], 1):
        tag = c["platform"].upper()
        game = f" ({c['game']})" if c["game"] else ""
        print(f"  {i:2}. [{tag:7}] [{c['view_count']:>9,} views] {c['title']!r} — {c['channel']}{game}")


if __name__ == "__main__":
    write_seed()
